### ISSUE TITLE
Bug: AttributeError: 'str' object has no attribute 'isdir'

### ISSUE THREAD

**Issue by Chlerry** [Chlerry/Video-Frame-Interpolation#18]
Error showing up when calling `load_image` and `save_image`  
```
Traceback (most recent call last):
  File ".\__main__.py", line 10, in <module>
    train_image = img_loader.load_image(path, 1, 1)
  File ".\Video-Frame-Interpolation\helper.py", line 12, in load_image
    if not(path.isdir(path)):
AttributeError: 'str' object has no attribute 'isdir'
```
https://github.com/Chlerry/Video-Frame-Interpolation/blob/8bdaec259b5ddfd4e9744da3ded2220abbb8232b/helper.py#L10-L14

https://github.com/Chlerry/Video-Frame-Interpolation/blob/8bdaec259b5ddfd4e9744da3ded2220abbb8232b/helper.py#L29-L33

**Comment by Chlerry** [comment]
Error showing up when calling `load_image` and `save_image`
```
Traceback (most recent call last):
  File ".\__main__.py", line 8, in <module>
    train_image = img_loader.load_image("./dataset/vimeo_triplet/", 1, 2)
  File ".\Video-Frame-Interpolation\helper.py", line 20, in load_image
    if not(os.path.isFile(path.format(set_num, image_num))):
AttributeError: module 'ntpath' has no attribute 'isFile'
```
https://github.com/Chlerry/Video-Frame-Interpolation/blob/8bdaec259b5ddfd4e9744da3ded2220abbb8232b/helper.py#L20
